version: '3.9'
services:
  test-database:
    container_name: test-database
    build:
      context: ./packages/database/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "prisma"
      MYSQL_ROOT_PASSWORD: "prisma"